all:
  vars:
    ansible_port: 22
    project_name: vps
    project_state: vps
  children:
    # Hosting location
    nodes:
      hosts:
        vps_vpn:
          ansible_host: 91.149.240.49
          server_name: VPS_VPN
        vps_grafana:
          ansible_host: 91.149.241.155
          server_name: VPS_GRAFANA
        vps_zabbix:
          ansible_host: 104.166.126.179
          server_name: VPS_ZABBIX
          vps_test:
          ansible_host: 91.149.240.129
          server_name: VPS_TEST

    #VPN
    vpn:
      hosts:
        vps_vpn:

    #Zabbix
    zabbix:
      hosts:
        vps_zabbix:
    
    #Grafana
    grafana:
      hosts:
        vps_grafana:

    #Test
    test:
      hosts:
        vps_test:
