all:
  vars:
    ansible_port: 22
    project_name: vps
    project_state: vps
  children:
    # Hosting location
    nodes:
      hosts:
        vps_vpn:
          ansible_host: 91.149.240.49
        vps_grafana:
          ansible_host: 91.149.241.155
        vps_zabbix:
          ansible_host: 104.166.126.179

    #VPN
    vpn:
      hosts:
        vps_vpn:

    #Zabbix
    zabbix:
      hosts:
        vps_zabbix:
    
    #Grafana
    grafana:
      hosts:
        vps_grafana:
