---
- name: install nginx
  apt:
    pkg: nginx
    state: latest

- name: install nginx
  apt:
    pkg: nginx
    state: latest

- name: Copy index.html
  copy:
    src: index.html
    dest: "{{root_dir}}"
    owner: root

- name: Copy nginx.conf
  template:
    src: nginx.conf.j2
    dest: /etc/nginx/nginx.conf
    mode: '0664'
  notify: restart nginx
