- hosts: all
  gather_facts: no
  vars:
    path: /var/log/upstart/nginx.log
  tasks:
    - ansible.builtin.debug: msg={{ '192.0.2.1/24', 'localhost' | ansible.utils.ipaddr('address') }}
    - ansible.builtin.debug: msg={{ 'test1' | hash('sha1') }} #SHA-1 (Secure Hash Algorithm 1) 
    - ansible.builtin.debug: msg={{ path | basename }} #Returns the last name component of a path, what is left in the string that is not ‘dirname’
    - ansible.builtin.debug: msg={{ path | dirname }}
    - ansible.builtin.debug: msg={{ "~/zabbix" | expanduser }} #Translates ~ in a path to the proper user’s home directory
    - ansible.builtin.debug: msg={{ 'cowsay_results' | split(',') }}
    