---
- name: Create new user
  user:
    name: "{{ item }}"
    shell: /bin/bash
    create_home: true
  loop: "{{ users }}"

- name: Create .ssh folder
  file:
      path: "~{{ item }}/.ssh"
      state: directory
      owner: "{{ item }}"
      group: "{{ item }}"
      mode: 0700
  loop: "{{ users }}"

- name: Upload SSH key
  copy:
    remote_src: false
    src: "{{ item }}"
    dest: "~{{ item }}/.ssh/authorized_keys"
    owner: "{{ item }}"
    group: "{{ item }}"
    mode: 0700
  loop: "{{ users }}"
  ignore_errors: yes

- name: add gitconfg
  template:
    src: gitconfig.j2
    dest: "/home/{{ item }}/.gitconfig"
    owner: root
  loop: "{{ users }}"
