---
#  - name: "Create users {{ users }}"
#    ansible.builtin.user:
#     name: "{{ item }}"
#    loop: "{{ users }}"
#    register: result

- name: create users
  user:
    name: "{{ item }}"
    shell: /bin/bash
    create_home: true
  loop: "{{ users }}"

- name: add gitconfg
  template:
    src: gitconfig.j2
    dest: "/home/{{ item }}/.gitconfig"
    owner: root
  loop: "{{ users }}"
