---
- name: Gather available local users
  getent:
    database: passwd

- name: Show gathered local user names only
  debug:
    msg: "{{ item }}"
  loop: "{{ getent_passwd.keys() | list }}"
  when: ansible_check_mode

- name: Check if local user account '{{ username }}' exists
  assert:
    that:
    - username in getent_passwd.keys()
    fail_msg: "Given user not exists!"
    success_msg: "Given user exists."
  register: result_answer
  changed_when: false
  failed_when: false
  
- name: show register result
  debug:
    msg: "{{ result_answer }}"
  
- name: Create new user
  when: result_answer.msg=="Given user not exists!"
  user:
   name: "{{ username }}"
   shell: /bin/bash
   create_home: true
   home: "/home/{{ username }}"
  register: new_user

- name: Delete new user
  when: result_answer.msg=="Given user exists."
  user:
    name: "{{ username }}"
    shell: /bin/bash
    state: absent
  register: delete_user

- name: Create .ssh folder
  when: new_user is defined
  file:
      path: "~{{ username }}/.ssh"
      state: directory
      owner: "{{ username }}"
      group: "{{ username }}"
      mode: 0700

- name: install git
  when: new_user is defined
  apt:
    name: git
    state: present

- name: add gitconfg
  when: new_user is defined
  template:
    src: gitconfig.j2
    dest: "/home/{{ username }}/.gitconfig"
    owner: "{{ username }}"
