---
- name: Gather facts
  gather_facts:
    parallel: true

- name: install git
  apt:
    name: git
    state: present

# - name: ensures {{  new_user }}/.gitconfig exists
#   file: 
#     path: "/home/{{ new_user }}/.gitconfig"
#     state: directory

- name: Add app directory
  file:
    path: "/home/{{ new_user }}/.gitconfig"
    state: directory
    mode: '0700'
    owner: "{{ new_user }}"
    group: "{{ new_user }}"

- name: add gitconfg
  template:
    src: gitconfig.j2
    dest: "/home/{{ new_user }}/.gitconfig"
    owner: "{{ new_user }}"
