---
- name: Gather facts
  gather_facts:
    parallel: true

- name: install git
  apt:
    name: git
    state: present

- name: Create /.gitconfig file
  template:
    remote_src: false
    src: gitconfig-new.j2
    dest: "/home/{{ new_user }}/.gitconfig"
    mode: '0600'
    owner: root
    unsafe_writes: true

# - name: finish installation
#   meta: end_play
